apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    openshift.io/installed-from: tektonhub
    tekton.dev/categories: Messaging
    tekton.dev/displayName: Send message to Microsoft Teams Channel
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le'
    tekton.dev/tags: messaging
  name: multi-massage-send-to-microsoft-teams
  namespace: board-dev
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: |-
    These tasks post a simple message to a Microsoft Teams Channel.
    This task uses the Incoming Webhook functionality of Microsoft Teams
  params:
    - description: Name of the secret with incoming webhook URL
      name: webhook-url-secret
      type: string
    - description: Key in the secret
      name: webhook-url-secret-key
      type: string
    - description: The message1 to notify about
      name: message1
      type: string
    - description: The message1 to notify about
      name: message2
      type: string
    - description: The message1 to notify about
      name: message3
      type: string
  steps:
    - env:
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: $(params.webhook-url-secret-key)
              name: $(params.webhook-url-secret)
        - name: MESSAGE1
          value: $(params.message1)
        - name: MESSAGE2
          value: $(params.message2)
        - name: MESSAGE3
          value: $(params.message3)
      image: >-
        docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4
      name: post
      resources: {}
      script: >
        #!/usr/bin/env sh

        MESSAGE1=$(echo "${MESSAGE1}" | sed -e 's/\"/\\\\"/g')

        JSON="{\"text\": \"${MESSAGE1}\" }"

        curl -X POST -H 'Content-Type: application/json' -d "${JSON}"
        "${WEBHOOK_URL}"

        MESSAGE2=$(echo "${MESSAGE2}" | sed -e 's/\"/\\\\"/g')

        JSON="{\"text\": \"${MESSAGE2}\" }"

        curl -X POST -H 'Content-Type: application/json' -d "${JSON}"
        "${WEBHOOK_URL}"

        MESSAGE3=$(echo "${MESSAGE3}" | sed -e 's/\"/\\\\"/g')

        JSON="{\"text\": \"${MESSAGE3}\" }"

        curl -X POST -H 'Content-Type: application/json' -d "${JSON}"
        "${WEBHOOK_URL}"
