apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
patches:
- patch: |-
  - op: replace
    path: /metadata/name
    value: board-qa
  target:
    kind: Namespace
    name: test
bases:
- ../base