apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: maven-settings
  files:
  - settings.xml
nameSuffix: -qa
resources:
- ../base
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: image-registry.openshift-image-registry.svc:5000/board-qa/board-app:init
  target:
    kind: Deployment