apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -qa
resources:
- ../base

## 변경될 부분 지정
patches:
  - path: patch/namespace-patch.yaml
    target:
      kind: Namespace
  - path: patch/patch.yaml
    target:
      kind: Deployment