apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: maven-settings
  files:
  - maven-settings/settings.xml
- name: sonar-settings
  files:
  - sonar-settings/settings.xml
resources:
- namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- pipeline.yaml
- source-pvc.yaml
- analyzer-pvc.yaml